export enum Opcode {
  // Access
  //// Load Accumulator
  LOAD_ACCUMULATOR_IMMEDIATE = 0xa9,
  LOAD_ACCUMULATOR_ZERO_PAGE = 0xa5,
  LOAD_ACCUMULATOR_ZERO_PAGE_X = 0xb5,
  LOAD_ACCUMULATOR_ABSOLUTE = 0xad,
  LOAD_ACCUMULATOR_ABSOLUTE_X = 0xbd,
  LOAD_ACCUMULATOR_ABSOLUTE_Y = 0xb9,
  LOAD_ACCUMULATOR_INDIRECT_X = 0xa1,
  LOAD_ACCUMULATOR_INDIRECT_Y = 0xb1,

  //// Load X Register
  LOAD_X_REGISTER_IMMEDIATE = 0xa2,
  LOAD_X_REGISTER_ZERO_PAGE = 0xa6,
  LOAD_X_REGISTER_ZERO_PAGE_Y = 0xb6,
  LOAD_X_REGISTER_ABSOLUTE = 0xae,
  LOAD_X_REGISTER_ABSOLUTE_Y = 0xbe,

  //// Load Y Register
  LOAD_Y_REGISTER_IMMEDIATE = 0xa0,
  LOAD_Y_REGISTER_ZERO_PAGE = 0xa4,
  LOAD_Y_REGISTER_ZERO_PAGE_X = 0xb4,
  LOAD_Y_REGISTER_ABSOLUTE = 0xac,
  LOAD_Y_REGISTER_ABSOLUTE_X = 0xbc,

  //// Store Accumulator
  STORE_ACCUMULATOR_ZERO_PAGE = 0x85,
  STORE_ACCUMULATOR_ZERO_PAGE_X = 0x95,
  STORE_ACCUMULATOR_ABSOLUTE = 0x8d,
  STORE_ACCUMULATOR_ABSOLUTE_X = 0x9d,
  STORE_ACCUMULATOR_ABSOLUTE_Y = 0x99,
  STORE_ACCUMULATOR_INDIRECT_X = 0x81,
  STORE_ACCUMULATOR_INDIRECT_Y = 0x91,

  //// Store X Register
  STORE_Y_REGISTER_ZERO_PAGE = 0x84,
  STORE_Y_REGISTER_ZERO_PAGE_X = 0x94,
  STORE_Y_REGISTER_ABSOLUTE = 0x8c,

  //// Store Y Register
  STORE_X_REGISTER_ZERO_PAGE = 0x86,
  STORE_X_REGISTER_ZERO_PAGE_Y = 0x96,
  STORE_X_REGISTER_ABSOLUTE = 0x8e,

  // Transfer
  //// X Register <-> Accumulator
  TRANSFER_ACCUMULATOR_TO_X_REGISTER = 0xaa,
  TRANSFER_X_REGISTER_TO_ACCUMULATOR = 0x8a,

  //// Y Register <-> Accumulator
  TRANSFER_ACCUMULATOR_TO_Y_REGISTER = 0xa8,
  TRANSFER_Y_REGISTER_TO_ACCUMULATOR = 0x98,

  // Arithmetic
  //// Increment
  INCREMENT_X_REGISTER = 0xe8,
  INCREMENT_Y_REGISTER = 0xc8,

  //// Decrement
  DECREMENT_X_REGISTER = 0xca,
  DECREMENT_Y_REGISTER = 0x88,

  //// Increment Memory
  INCREMENT_MEMORY_ZERO_PAGE = 0xe6,
  INCREMENT_MEMORY_ZERO_PAGE_X = 0xf6,
  INCREMENT_MEMORY_ABSOLUTE = 0xee,
  INCREMENT_MEMORY_ABSOLUTE_X = 0xfe,

  //// Decrement Memory
  DECREMENT_MEMORY_ZERO_PAGE = 0xc6,
  DECREMENT_MEMORY_ZERO_PAGE_X = 0xd6,
  DECREMENT_MEMORY_ABSOLUTE = 0xce,
  DECREMENT_MEMORY_ABSOLUTE_X = 0xde,

  //// Add with Carry
  ADD_WITH_CARRY_IMMEDIATE = 0x69,
  ADD_WITH_CARRY_ZERO_PAGE = 0x65,
  ADD_WITH_CARRY_ZERO_PAGE_X = 0x75,
  ADD_WITH_CARRY_ABSOLUTE = 0x6d,
  ADD_WITH_CARRY_ABSOLUTE_X = 0x7d,
  ADD_WITH_CARRY_ABSOLUTE_Y = 0x79,
  ADD_WITH_CARRY_INDIRECT_X = 0x61,
  ADD_WITH_CARRY_INDIRECT_Y = 0x71,

  //// Subtract with Carry
  SUBTRACT_WITH_CARRY_IMMEDIATE = 0xe9,
  SUBTRACT_WITH_CARRY_ZERO_PAGE = 0xe5,
  SUBTRACT_WITH_CARRY_ZERO_PAGE_X = 0xf5,
  SUBTRACT_WITH_CARRY_ABSOLUTE = 0xed,
  SUBTRACT_WITH_CARRY_ABSOLUTE_X = 0xfd,
  SUBTRACT_WITH_CARRY_ABSOLUTE_Y = 0xf9,
  SUBTRACT_WITH_CARRY_INDIRECT_X = 0xe1,
  SUBTRACT_WITH_CARRY_INDIRECT_Y = 0xf1,

  // Shift
  //// Arithmetic Shift Left
  ARITHMETIC_SHIFT_LEFT_ACCUMULATOR = 0x0a,
  ARITHMETIC_SHIFT_LEFT_ZERO_PAGE = 0x06,
  ARITHMETIC_SHIFT_LEFT_ZERO_PAGE_X = 0x16,
  ARITHMETIC_SHIFT_LEFT_ABSOLUTE = 0x0e,
  ARITHMETIC_SHIFT_LEFT_ABSOLUTE_X = 0x1e,

  //// Logical Shift Right
  LOGICAL_SHIFT_RIGHT_ACCUMULATOR = 0x4a,
  LOGICAL_SHIFT_RIGHT_ZERO_PAGE = 0x46,
  LOGICAL_SHIFT_RIGHT_ZERO_PAGE_X = 0x56,
  LOGICAL_SHIFT_RIGHT_ABSOLUTE = 0x4e,
  LOGICAL_SHIFT_RIGHT_ABSOLUTE_X = 0x5e,

  //// Rotate Left
  ROTATE_LEFT_ACCUMULATOR = 0x2a,
  ROTATE_LEFT_ZERO_PAGE = 0x26,
  ROTATE_LEFT_ZERO_PAGE_X = 0x36,
  ROTATE_LEFT_ABSOLUTE = 0x2e,
  ROTATE_LEFT_ABSOLUTE_X = 0x3e,

  //// Rotate Right
  ROTATE_RIGHT_ACCUMULATOR = 0x6a,
  ROTATE_RIGHT_ZERO_PAGE = 0x66,
  ROTATE_RIGHT_ZERO_PAGE_X = 0x76,
  ROTATE_RIGHT_ABSOLUTE = 0x6e,
  ROTATE_RIGHT_ABSOLUTE_X = 0x7e,

  // Bitwise
  //// Bitwise AND
  BITWISE_AND_IMMEDIATE = 0x29,
  BITWISE_AND_ZERO_PAGE = 0x25,
  BITWISE_AND_ZERO_PAGE_X = 0x35,
  BITWISE_AND_ABSOLUTE = 0x2d,
  BITWISE_AND_ABSOLUTE_X = 0x3d,
  BITWISE_AND_ABSOLUTE_Y = 0x39,
  BITWISE_AND_INDIRECT_X = 0x21,
  BITWISE_AND_INDIRECT_Y = 0x31,

  //// Bitwise OR
  BITWISE_OR_IMMEDIATE = 0x09,
  BITWISE_OR_ZERO_PAGE = 0x05,
  BITWISE_OR_ZERO_PAGE_X = 0x15,
  BITWISE_OR_ABSOLUTE = 0x0d,
  BITWISE_OR_ABSOLUTE_X = 0x1d,
  BITWISE_OR_ABSOLUTE_Y = 0x19,
  BITWISE_OR_INDIRECT_X = 0x01,
  BITWISE_OR_INDIRECT_Y = 0x11,

  //// Bitwise Exclusive OR
  BITWISE_EXCLUSIVE_OR_IMMEDIATE = 0x49,
  BITWISE_EXCLUSIVE_OR_ZERO_PAGE = 0x45,
  BITWISE_EXCLUSIVE_OR_ZERO_PAGE_X = 0x55,
  BITWISE_EXCLUSIVE_OR_ABSOLUTE = 0x4d,
  BITWISE_EXCLUSIVE_OR_ABSOLUTE_X = 0x5d,
  BITWISE_EXCLUSIVE_OR_ABSOLUTE_Y = 0x59,
  BITWISE_EXCLUSIVE_OR_INDIRECT_X = 0x41,
  BITWISE_EXCLUSIVE_OR_INDIRECT_Y = 0x51,

  //// Bit Test
  BIT_TEST_ZERO_PAGE = 0x24,
  BIT_TEST_ABSOLUTE = 0x2c,

  // Compare
  //// Compare Accumulator
  COMPARE_ACCUMULATOR_IMMEDIATE = 0xc9,
  COMPARE_ACCUMULATOR_ZERO_PAGE = 0xc5,
  COMPARE_ACCUMULATOR_ZERO_PAGE_X = 0xd5,
  COMPARE_ACCUMULATOR_ABSOLUTE = 0xcd,
  COMPARE_ACCUMULATOR_ABSOLUTE_X = 0xdd,
  COMPARE_ACCUMULATOR_ABSOLUTE_Y = 0xd9,
  COMPARE_ACCUMULATOR_INDIRECT_X = 0xc1,
  COMPARE_ACCUMULATOR_INDIRECT_Y = 0xd1,

  //// Compare X Register
  COMPARE_X_REGISTER_IMMEDIATE = 0xe0,
  COMPARE_X_REGISTER_ZERO_PAGE = 0xe4,
  COMPARE_X_REGISTER_ABSOLUTE = 0xec,

  //// Compare Y Register
  COMPARE_Y_REGISTER_IMMEDIATE = 0xc0,
  COMPARE_Y_REGISTER_ZERO_PAGE = 0xc4,
  COMPARE_Y_REGISTER_ABSOLUTE = 0xcc,

  // Branch
  //// Zero Flag
  BRANCH_IF_EQUAL = 0xf0,
  BRANCH_IF_NOT_EQUAL = 0xd0,

  //// Carry Flag
  BRANCH_IF_CARRY_SET = 0xb0,
  BRANCH_IF_CARRY_CLEAR = 0x90,

  //// Negative Flag
  BRANCH_IF_MINUS = 0x30,
  BRANCH_IF_POSITIVE = 0x10,

  //// Overflow Flag
  BRANCH_IF_OVERFLOW_SET = 0x70,
  BRANCH_IF_OVERFLOW_CLEAR = 0x50,

  // Jump
  //// Jump
  JUMP_ABSOLUTE = 0x4c,
  JUMP_INDIRECT = 0x6c,

  //// Jump to Subroutine
  JUMP_TO_SUBROUTINE = 0x20,

  //// Return From Subroutine
  RETURN_FROM_SUBROUTINE = 0x60,

  //// Break
  BREAK = 0x00,

  //// Return From Interrupt
  RETURN_FROM_INTERRUPT = 0x40,

  // Stack
  //// Stack Accumulator
  STACK_PUSH_ACCUMULATOR = 0x48,
  STACK_PULL_ACCUMULATOR = 0x68,

  //// Stack Processor Status
  STACK_PUSH_PROCESSOR_STATUS = 0x08,
  STACK_PULL_PROCESSOR_STATUS = 0x28,

  //// X Register <-> Stack Pointer
  TRANSFER_STACK_POINTER_TO_X_REGISTER = 0xba,
  TRANSFER_X_REGISTER_TO_STACK_POINTER = 0x9a,

  // Flag
  //// Carry
  CLEAR_CARRY_FLAG = 0x18,
  SET_CARRY_FLAG = 0x38,

  //// Interrupt
  CLEAR_INTERRUPT_FLAG = 0x58,
  SET_INTERRUPT_FLAG = 0x78,

  //// Decimal
  CLEAR_DECIMAL_FLAG = 0xd8,
  SET_DECIMAL_FLAG = 0xf8,

  //// Overflow
  CLEAR_OVERFLOW_FLAG = 0xb8,

  // Other
  //// System
  NO_OPERATION = 0xea,

  // Illegal
  //// NOP (illegal)
  ////// Immediate
  NO_OPERATION_IMMEDIATE = 0x80,

  ////// Zero Page
  NO_OPERATION_ZERO_PAGE_04 = 0x04,
  NO_OPERATION_ZERO_PAGE_44 = 0x44,
  NO_OPERATION_ZERO_PAGE_64 = 0x64,

  ////// Zero Page,X
  NO_OPERATION_ZERO_X_14 = 0x14,
  NO_OPERATION_ZERO_X_34 = 0x34,
  NO_OPERATION_ZERO_X_54 = 0x54,
  NO_OPERATION_ZERO_X_74 = 0x74,
  NO_OPERATION_ZERO_X_D4 = 0xd4,
  NO_OPERATION_ZERO_X_F4 = 0xf4,

  ////// Absolute
  NO_OPERATION_ABSOLUTE = 0x0c,

  ////// Absolute,X
  NO_OPERATION_ABSOLUTE_X_1C = 0x1c,
  NO_OPERATION_ABSOLUTE_X_3C = 0x3c,
  NO_OPERATION_ABSOLUTE_X_5C = 0x5c,
  NO_OPERATION_ABSOLUTE_X_7C = 0x7c,
  NO_OPERATION_ABSOLUTE_X_DC = 0xdc,
  NO_OPERATION_ABSOLUTE_X_FC = 0xfc,

  ////// Implied (ilegais)
  NO_OPERATION_1A = 0x1a,
  NO_OPERATION_3A = 0x3a,
  NO_OPERATION_5A = 0x5a,
  NO_OPERATION_7A = 0x7a,
  NO_OPERATION_DA = 0xda,
  NO_OPERATION_FA = 0xfa,

  //// Load Accumulator And X Register
  LOAD_ACCUMULATOR_AND_X_REGISTER_ZERO_PAGE = 0xa7,
  LOAD_ACCUMULATOR_AND_X_REGISTER_ZERO_PAGE_Y = 0xb7,
  LOAD_ACCUMULATOR_AND_X_REGISTER_ABSOLUTE = 0xaf,
  LOAD_ACCUMULATOR_AND_X_REGISTER_ABSOLUTE_Y = 0xbf,
  LOAD_ACCUMULATOR_AND_X_REGISTER_INDIRECT_X = 0xa3,
  LOAD_ACCUMULATOR_AND_X_REGISTER_INDIRECT_Y = 0xb3,

  //// Store Accumulator
  STORE_ACCUMULATOR_AND_X_REGISTER_ZERO_PAGE = 0x87,
  STORE_ACCUMULATOR_AND_X_REGISTER_ZERO_PAGE_Y = 0x97,
  STORE_ACCUMULATOR_AND_X_REGISTER_ABSOLUTE = 0x8f,
  STORE_ACCUMULATOR_AND_X_REGISTER_INDIRECT_X = 0x83,

  //// Subtract with Carry
  SUBTRACT_WITH_CARRY_IMMEDIATE_EB = 0xeb,

  //// Decrement Memory then Compare Accumulator (DCP - illegal opcode)
  DECREMENT_AND_COMPARE_ACCUMULATOR_ZERO_PAGE = 0xc7,
  DECREMENT_AND_COMPARE_ACCUMULATOR_ZERO_PAGE_X = 0xd7,
  DECREMENT_AND_COMPARE_ACCUMULATOR_ABSOLUTE = 0xcf,
  DECREMENT_AND_COMPARE_ACCUMULATOR_ABSOLUTE_X = 0xdf,
  DECREMENT_AND_COMPARE_ACCUMULATOR_ABSOLUTE_Y = 0xdb,
  DECREMENT_AND_COMPARE_ACCUMULATOR_INDIRECT_X = 0xc3,
  DECREMENT_AND_COMPARE_ACCUMULATOR_INDIRECT_Y = 0xd3,

  //// Increment Memory then Subtract with Carry (ISC - illegal opcode)
  INCREMENT_AND_SUBTRACT_WITH_CARRY_ZERO_PAGE = 0xe7,
  INCREMENT_AND_SUBTRACT_WITH_CARRY_ZERO_PAGE_X = 0xf7,
  INCREMENT_AND_SUBTRACT_WITH_CARRY_ABSOLUTE = 0xef,
  INCREMENT_AND_SUBTRACT_WITH_CARRY_ABSOLUTE_X = 0xff,
  INCREMENT_AND_SUBTRACT_WITH_CARRY_ABSOLUTE_Y = 0xfb,
  INCREMENT_AND_SUBTRACT_WITH_CARRY_INDIRECT_X = 0xe3,
  INCREMENT_AND_SUBTRACT_WITH_CARRY_INDIRECT_Y = 0xf3,

  //// Shift Left then OR with Accumulator (SLO - illegal opcode)
  SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ZERO_PAGE = 0x07,
  SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ZERO_PAGE_X = 0x17,
  SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ABSOLUTE = 0x0f,
  SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ABSOLUTE_X = 0x1f,
  SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ABSOLUTE_Y = 0x1b,
  SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_INDIRECT_X = 0x03,
  SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_INDIRECT_Y = 0x13,

  //// Rotate Left then AND with Accumulator (RLA - illegal opcode)
  ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ZERO_PAGE = 0x27,
  ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ZERO_PAGE_X = 0x37,
  ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ABSOLUTE = 0x2f,
  ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ABSOLUTE_X = 0x3f,
  ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ABSOLUTE_Y = 0x3b,
  ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_INDIRECT_X = 0x23,
  ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_INDIRECT_Y = 0x33,

  //// Shift Right then XOR with Accumulator (SRE - illegal opcode)
  SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ZERO_PAGE = 0x47,
  SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ZERO_PAGE_X = 0x57,
  SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ABSOLUTE = 0x4f,
  SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ABSOLUTE_X = 0x5f,
  SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ABSOLUTE_Y = 0x5b,
  SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_INDIRECT_X = 0x43,
  SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_INDIRECT_Y = 0x53,

  //// Rotate Right then Add with Accumulator (RRA - illegal opcode)
  ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ZERO_PAGE = 0x67,
  ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ZERO_PAGE_X = 0x77,
  ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ABSOLUTE = 0x6f,
  ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ABSOLUTE_X = 0x7f,
  ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ABSOLUTE_Y = 0x7b,
  ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_INDIRECT_X = 0x63,
  ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_INDIRECT_Y = 0x73,
}

export type AccessOpcode =
  // Load Accumulator
  | Opcode.LOAD_ACCUMULATOR_IMMEDIATE
  | Opcode.LOAD_ACCUMULATOR_ZERO_PAGE
  | Opcode.LOAD_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.LOAD_ACCUMULATOR_ABSOLUTE
  | Opcode.LOAD_ACCUMULATOR_ABSOLUTE_X
  | Opcode.LOAD_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.LOAD_ACCUMULATOR_INDIRECT_X
  | Opcode.LOAD_ACCUMULATOR_INDIRECT_Y

  // Load X Register
  | Opcode.LOAD_X_REGISTER_IMMEDIATE
  | Opcode.LOAD_X_REGISTER_ZERO_PAGE
  | Opcode.LOAD_X_REGISTER_ZERO_PAGE_Y
  | Opcode.LOAD_X_REGISTER_ABSOLUTE
  | Opcode.LOAD_X_REGISTER_ABSOLUTE_Y

  // Load Y Register
  | Opcode.LOAD_Y_REGISTER_IMMEDIATE
  | Opcode.LOAD_Y_REGISTER_ZERO_PAGE
  | Opcode.LOAD_Y_REGISTER_ZERO_PAGE_X
  | Opcode.LOAD_Y_REGISTER_ABSOLUTE
  | Opcode.LOAD_Y_REGISTER_ABSOLUTE_X

  // Store Accumulator
  | Opcode.STORE_ACCUMULATOR_ZERO_PAGE
  | Opcode.STORE_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.STORE_ACCUMULATOR_ABSOLUTE
  | Opcode.STORE_ACCUMULATOR_ABSOLUTE_X
  | Opcode.STORE_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.STORE_ACCUMULATOR_INDIRECT_X
  | Opcode.STORE_ACCUMULATOR_INDIRECT_Y

  // Store X Register
  | Opcode.STORE_X_REGISTER_ZERO_PAGE
  | Opcode.STORE_X_REGISTER_ZERO_PAGE_Y
  | Opcode.STORE_X_REGISTER_ABSOLUTE

  // Store Y Register
  | Opcode.STORE_Y_REGISTER_ZERO_PAGE
  | Opcode.STORE_Y_REGISTER_ZERO_PAGE_X
  | Opcode.STORE_Y_REGISTER_ABSOLUTE;

export type TransferOpcode =
  // X Register <-> Accumulator
  | Opcode.TRANSFER_ACCUMULATOR_TO_X_REGISTER
  | Opcode.TRANSFER_X_REGISTER_TO_ACCUMULATOR

  // Y Register <-> Accumulator
  | Opcode.TRANSFER_ACCUMULATOR_TO_Y_REGISTER
  | Opcode.TRANSFER_Y_REGISTER_TO_ACCUMULATOR;

export type ArithmeticOpcode =
  // Increment
  | Opcode.INCREMENT_X_REGISTER
  | Opcode.INCREMENT_Y_REGISTER

  // Decrement
  | Opcode.DECREMENT_X_REGISTER
  | Opcode.DECREMENT_Y_REGISTER

  // Increment Memory
  | Opcode.INCREMENT_MEMORY_ZERO_PAGE
  | Opcode.INCREMENT_MEMORY_ZERO_PAGE_X
  | Opcode.INCREMENT_MEMORY_ABSOLUTE
  | Opcode.INCREMENT_MEMORY_ABSOLUTE_X

  // Decrement Memory
  | Opcode.DECREMENT_MEMORY_ZERO_PAGE
  | Opcode.DECREMENT_MEMORY_ZERO_PAGE_X
  | Opcode.DECREMENT_MEMORY_ABSOLUTE
  | Opcode.DECREMENT_MEMORY_ABSOLUTE_X

  // Add with Carry
  | Opcode.ADD_WITH_CARRY_IMMEDIATE
  | Opcode.ADD_WITH_CARRY_ZERO_PAGE
  | Opcode.ADD_WITH_CARRY_ZERO_PAGE_X
  | Opcode.ADD_WITH_CARRY_ABSOLUTE
  | Opcode.ADD_WITH_CARRY_ABSOLUTE_X
  | Opcode.ADD_WITH_CARRY_ABSOLUTE_Y
  | Opcode.ADD_WITH_CARRY_INDIRECT_X
  | Opcode.ADD_WITH_CARRY_INDIRECT_Y

  // Subtract with Carry
  | Opcode.SUBTRACT_WITH_CARRY_IMMEDIATE
  | Opcode.SUBTRACT_WITH_CARRY_ZERO_PAGE
  | Opcode.SUBTRACT_WITH_CARRY_ZERO_PAGE_X
  | Opcode.SUBTRACT_WITH_CARRY_ABSOLUTE
  | Opcode.SUBTRACT_WITH_CARRY_ABSOLUTE_X
  | Opcode.SUBTRACT_WITH_CARRY_ABSOLUTE_Y
  | Opcode.SUBTRACT_WITH_CARRY_INDIRECT_X
  | Opcode.SUBTRACT_WITH_CARRY_INDIRECT_Y;

export type ShiftOpcode =
  // Arithmetic Shift Left
  | Opcode.ARITHMETIC_SHIFT_LEFT_ACCUMULATOR
  | Opcode.ARITHMETIC_SHIFT_LEFT_ZERO_PAGE
  | Opcode.ARITHMETIC_SHIFT_LEFT_ZERO_PAGE_X
  | Opcode.ARITHMETIC_SHIFT_LEFT_ABSOLUTE
  | Opcode.ARITHMETIC_SHIFT_LEFT_ABSOLUTE_X

  // Logical Shift Right
  | Opcode.LOGICAL_SHIFT_RIGHT_ACCUMULATOR
  | Opcode.LOGICAL_SHIFT_RIGHT_ZERO_PAGE
  | Opcode.LOGICAL_SHIFT_RIGHT_ZERO_PAGE_X
  | Opcode.LOGICAL_SHIFT_RIGHT_ABSOLUTE
  | Opcode.LOGICAL_SHIFT_RIGHT_ABSOLUTE_X

  // Rotate Left
  | Opcode.ROTATE_LEFT_ACCUMULATOR
  | Opcode.ROTATE_LEFT_ZERO_PAGE
  | Opcode.ROTATE_LEFT_ZERO_PAGE_X
  | Opcode.ROTATE_LEFT_ABSOLUTE
  | Opcode.ROTATE_LEFT_ABSOLUTE_X

  // Rotate Right
  | Opcode.ROTATE_RIGHT_ACCUMULATOR
  | Opcode.ROTATE_RIGHT_ZERO_PAGE
  | Opcode.ROTATE_RIGHT_ZERO_PAGE_X
  | Opcode.ROTATE_RIGHT_ABSOLUTE
  | Opcode.ROTATE_RIGHT_ABSOLUTE_X;

export type BitwiseOpcode =
  // Bitwise AND
  | Opcode.BITWISE_AND_IMMEDIATE
  | Opcode.BITWISE_AND_ZERO_PAGE
  | Opcode.BITWISE_AND_ZERO_PAGE_X
  | Opcode.BITWISE_AND_ABSOLUTE
  | Opcode.BITWISE_AND_ABSOLUTE_X
  | Opcode.BITWISE_AND_ABSOLUTE_Y
  | Opcode.BITWISE_AND_INDIRECT_X
  | Opcode.BITWISE_AND_INDIRECT_Y

  // Bitwise OR
  | Opcode.BITWISE_OR_IMMEDIATE
  | Opcode.BITWISE_OR_ZERO_PAGE
  | Opcode.BITWISE_OR_ZERO_PAGE_X
  | Opcode.BITWISE_OR_ABSOLUTE
  | Opcode.BITWISE_OR_ABSOLUTE_X
  | Opcode.BITWISE_OR_ABSOLUTE_Y
  | Opcode.BITWISE_OR_INDIRECT_X
  | Opcode.BITWISE_OR_INDIRECT_Y

  // Bitwise Exclusive OR
  | Opcode.BITWISE_EXCLUSIVE_OR_IMMEDIATE
  | Opcode.BITWISE_EXCLUSIVE_OR_ZERO_PAGE
  | Opcode.BITWISE_EXCLUSIVE_OR_ZERO_PAGE_X
  | Opcode.BITWISE_EXCLUSIVE_OR_ABSOLUTE
  | Opcode.BITWISE_EXCLUSIVE_OR_ABSOLUTE_X
  | Opcode.BITWISE_EXCLUSIVE_OR_ABSOLUTE_Y
  | Opcode.BITWISE_EXCLUSIVE_OR_INDIRECT_X
  | Opcode.BITWISE_EXCLUSIVE_OR_INDIRECT_Y

  // Bit Test
  | Opcode.BIT_TEST_ZERO_PAGE
  | Opcode.BIT_TEST_ABSOLUTE;

export type CompareOpcode =
  // Compare Accumulator
  | Opcode.COMPARE_ACCUMULATOR_IMMEDIATE
  | Opcode.COMPARE_ACCUMULATOR_ZERO_PAGE
  | Opcode.COMPARE_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.COMPARE_ACCUMULATOR_ABSOLUTE
  | Opcode.COMPARE_ACCUMULATOR_ABSOLUTE_X
  | Opcode.COMPARE_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.COMPARE_ACCUMULATOR_INDIRECT_X
  | Opcode.COMPARE_ACCUMULATOR_INDIRECT_Y

  // Compare X Register
  | Opcode.COMPARE_X_REGISTER_IMMEDIATE
  | Opcode.COMPARE_X_REGISTER_ZERO_PAGE
  | Opcode.COMPARE_X_REGISTER_ABSOLUTE

  // Compare Y Register
  | Opcode.COMPARE_Y_REGISTER_IMMEDIATE
  | Opcode.COMPARE_Y_REGISTER_ZERO_PAGE
  | Opcode.COMPARE_Y_REGISTER_ABSOLUTE;

export type BranchOpcode =
  // Zero Flag
  | Opcode.BRANCH_IF_EQUAL
  | Opcode.BRANCH_IF_NOT_EQUAL

  // Carry Flag
  | Opcode.BRANCH_IF_CARRY_SET
  | Opcode.BRANCH_IF_CARRY_CLEAR

  // Negative Flag
  | Opcode.BRANCH_IF_MINUS
  | Opcode.BRANCH_IF_POSITIVE

  // Overflow Flag
  | Opcode.BRANCH_IF_OVERFLOW_SET
  | Opcode.BRANCH_IF_OVERFLOW_CLEAR;

export type JumpOpcode =
  // Jump
  | Opcode.JUMP_ABSOLUTE
  | Opcode.JUMP_INDIRECT

  // Jump to Subroutine
  | Opcode.JUMP_TO_SUBROUTINE

  // Return From Subroutine
  | Opcode.RETURN_FROM_SUBROUTINE

  // Break
  | Opcode.BREAK

  // Return From Interrupt
  | Opcode.RETURN_FROM_INTERRUPT;

export type StackOpcode =
  // Stack Accumulator
  | Opcode.STACK_PUSH_ACCUMULATOR
  | Opcode.STACK_PULL_ACCUMULATOR

  // Stack Processor Status
  | Opcode.STACK_PUSH_PROCESSOR_STATUS
  | Opcode.STACK_PULL_PROCESSOR_STATUS

  // Transfer X Register <-> Stack Pointer
  | Opcode.TRANSFER_STACK_POINTER_TO_X_REGISTER
  | Opcode.TRANSFER_X_REGISTER_TO_STACK_POINTER;

export type FlagOpcode =
  //// Carry
  | Opcode.CLEAR_CARRY_FLAG
  | Opcode.SET_CARRY_FLAG

  //// Interrupt
  | Opcode.CLEAR_INTERRUPT_FLAG
  | Opcode.SET_INTERRUPT_FLAG

  //// Decimal
  | Opcode.CLEAR_DECIMAL_FLAG
  | Opcode.SET_DECIMAL_FLAG

  //// Overflow
  | Opcode.CLEAR_OVERFLOW_FLAG;

export type OtherOpcode =
  // System
  Opcode.NO_OPERATION;

export type IllegalOpcode =
  // NOP (ILEGAIS)

  //// Immediate
  | Opcode.NO_OPERATION_IMMEDIATE

  //// Zero Page
  | Opcode.NO_OPERATION_ZERO_PAGE_04
  | Opcode.NO_OPERATION_ZERO_PAGE_44
  | Opcode.NO_OPERATION_ZERO_PAGE_64

  //// Zero Page,X
  | Opcode.NO_OPERATION_ZERO_X_14
  | Opcode.NO_OPERATION_ZERO_X_34
  | Opcode.NO_OPERATION_ZERO_X_54
  | Opcode.NO_OPERATION_ZERO_X_74
  | Opcode.NO_OPERATION_ZERO_X_D4
  | Opcode.NO_OPERATION_ZERO_X_F4

  //// Absolute
  | Opcode.NO_OPERATION_ABSOLUTE

  //// Absolute,X
  | Opcode.NO_OPERATION_ABSOLUTE_X_1C
  | Opcode.NO_OPERATION_ABSOLUTE_X_3C
  | Opcode.NO_OPERATION_ABSOLUTE_X_5C
  | Opcode.NO_OPERATION_ABSOLUTE_X_7C
  | Opcode.NO_OPERATION_ABSOLUTE_X_DC
  | Opcode.NO_OPERATION_ABSOLUTE_X_FC

  //// Implied (ilegais)
  | Opcode.NO_OPERATION_1A
  | Opcode.NO_OPERATION_3A
  | Opcode.NO_OPERATION_5A
  | Opcode.NO_OPERATION_7A
  | Opcode.NO_OPERATION_DA
  | Opcode.NO_OPERATION_FA

  // Load Accumulator And X Register
  | Opcode.LOAD_ACCUMULATOR_AND_X_REGISTER_ZERO_PAGE
  | Opcode.LOAD_ACCUMULATOR_AND_X_REGISTER_ZERO_PAGE_Y
  | Opcode.LOAD_ACCUMULATOR_AND_X_REGISTER_ABSOLUTE
  | Opcode.LOAD_ACCUMULATOR_AND_X_REGISTER_ABSOLUTE_Y
  | Opcode.LOAD_ACCUMULATOR_AND_X_REGISTER_INDIRECT_X
  | Opcode.LOAD_ACCUMULATOR_AND_X_REGISTER_INDIRECT_Y

  // Store Accumulator
  | Opcode.STORE_ACCUMULATOR_AND_X_REGISTER_ZERO_PAGE
  | Opcode.STORE_ACCUMULATOR_AND_X_REGISTER_ZERO_PAGE_Y
  | Opcode.STORE_ACCUMULATOR_AND_X_REGISTER_ABSOLUTE
  | Opcode.STORE_ACCUMULATOR_AND_X_REGISTER_INDIRECT_X

  // Subtract with Carry
  | Opcode.SUBTRACT_WITH_CARRY_IMMEDIATE_EB

  // Decrement Memory then Compare Accumulator (DCP - illegal opcode)
  | Opcode.DECREMENT_AND_COMPARE_ACCUMULATOR_ZERO_PAGE
  | Opcode.DECREMENT_AND_COMPARE_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.DECREMENT_AND_COMPARE_ACCUMULATOR_ABSOLUTE
  | Opcode.DECREMENT_AND_COMPARE_ACCUMULATOR_ABSOLUTE_X
  | Opcode.DECREMENT_AND_COMPARE_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.DECREMENT_AND_COMPARE_ACCUMULATOR_INDIRECT_X
  | Opcode.DECREMENT_AND_COMPARE_ACCUMULATOR_INDIRECT_Y

  // Increment Memory then Subtract with Carry (ISC - illegal opcode)
  | Opcode.INCREMENT_AND_SUBTRACT_WITH_CARRY_ZERO_PAGE
  | Opcode.INCREMENT_AND_SUBTRACT_WITH_CARRY_ZERO_PAGE_X
  | Opcode.INCREMENT_AND_SUBTRACT_WITH_CARRY_ABSOLUTE
  | Opcode.INCREMENT_AND_SUBTRACT_WITH_CARRY_ABSOLUTE_X
  | Opcode.INCREMENT_AND_SUBTRACT_WITH_CARRY_ABSOLUTE_Y
  | Opcode.INCREMENT_AND_SUBTRACT_WITH_CARRY_INDIRECT_X
  | Opcode.INCREMENT_AND_SUBTRACT_WITH_CARRY_INDIRECT_Y

  // Shift Left then OR with Accumulator (SLO - illegal opcode)
  | Opcode.SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ZERO_PAGE
  | Opcode.SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ABSOLUTE
  | Opcode.SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ABSOLUTE_X
  | Opcode.SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_INDIRECT_X
  | Opcode.SHIFT_LEFT_AND_OR_WITH_ACCUMULATOR_INDIRECT_Y

  // Rotate Left then AND with Accumulator (RLA - illegal opcode)
  | Opcode.ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ZERO_PAGE
  | Opcode.ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ABSOLUTE
  | Opcode.ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ABSOLUTE_X
  | Opcode.ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_INDIRECT_X
  | Opcode.ROTATE_LEFT_AND_AND_WITH_ACCUMULATOR_INDIRECT_Y

  // Shift Right then XOR with Accumulator (SRE - illegal opcode)
  | Opcode.SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ZERO_PAGE
  | Opcode.SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ABSOLUTE
  | Opcode.SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ABSOLUTE_X
  | Opcode.SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_INDIRECT_X
  | Opcode.SHIFT_RIGHT_AND_XOR_WITH_ACCUMULATOR_INDIRECT_Y

  // Rotate Right then Add with Accumulator (RRA - illegal opcode)
  | Opcode.ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ZERO_PAGE
  | Opcode.ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ABSOLUTE
  | Opcode.ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ABSOLUTE_X
  | Opcode.ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_INDIRECT_X
  | Opcode.ROTATE_RIGHT_AND_ADD_WITH_ACCUMULATOR_INDIRECT_Y;
