export enum Opcode {
  // Access
  //// Load Accumulator
  LOAD_ACCUMULATOR_IMMEDIATE = 0xa9,
  LOAD_ACCUMULATOR_ZERO_PAGE = 0xa5,
  LOAD_ACCUMULATOR_ZERO_PAGE_X = 0xb5,
  LOAD_ACCUMULATOR_ABSOLUTE = 0xad,
  LOAD_ACCUMULATOR_ABSOLUTE_X = 0xbd,
  LOAD_ACCUMULATOR_ABSOLUTE_Y = 0xb9,
  LOAD_ACCUMULATOR_INDIRECT_X = 0xa1,
  LOAD_ACCUMULATOR_INDIRECT_Y = 0xb1,

  //// Load X Register
  LOAD_X_REGISTER_IMMEDIATE = 0xa2,
  LOAD_X_REGISTER_ZERO_PAGE = 0xa6,
  LOAD_X_REGISTER_ZERO_PAGE_Y = 0xb6,
  LOAD_X_REGISTER_ABSOLUTE = 0xae,
  LOAD_X_REGISTER_ABSOLUTE_Y = 0xbe,

  //// Load Y Register
  LOAD_Y_REGISTER_IMMEDIATE = 0xa0,
  LOAD_Y_REGISTER_ZERO_PAGE = 0xa4,
  LOAD_Y_REGISTER_ZERO_PAGE_X = 0xb4,
  LOAD_Y_REGISTER_ABSOLUTE = 0xac,
  LOAD_Y_REGISTER_ABSOLUTE_X = 0xbc,

  // Store Accumulator
  STORE_ACCUMULATOR_ZERO_PAGE = 0x85,
  STORE_ACCUMULATOR_ZERO_PAGE_X = 0x95,
  STORE_ACCUMULATOR_ABSOLUTE = 0x8d,
  STORE_ACCUMULATOR_ABSOLUTE_X = 0x9d,
  STORE_ACCUMULATOR_ABSOLUTE_Y = 0x99,
  STORE_ACCUMULATOR_INDIRECT_X = 0x81,
  STORE_ACCUMULATOR_INDIRECT_Y = 0x91,

  // Store X Register
  STORE_X_REGISTER_ZERO_PAGE = 0x84,
  STORE_X_REGISTER_ZERO_PAGE_Y = 0x94,
  STORE_X_REGISTER_ABSOLUTE = 0x8c,

  // Store Y Register
  STORE_Y_REGISTER_ZERO_PAGE = 0x86,
  STORE_Y_REGISTER_ZERO_PAGE_X = 0x96,
  STORE_Y_REGISTER_ABSOLUTE = 0x8e,

  //// Transfer
  // X Register <-> Accumulator
  TRANSFER_ACCUMULATOR_TO_X_REGISTER = 0xaa,
  TRANSFER_X_REGISTER_TO_ACCUMULATOR = 0x8a,

  // Y Register <-> Accumulator
  TRANSFER_ACCUMULATOR_TO_Y_REGISTER = 0xa8,
  TRANSFER_Y_REGISTER_TO_ACCUMULATOR = 0x98,

  //// Arithmetic
  // Increment
  INCREMENT_X_REGISTER = 0xe8,
  INCREMENT_Y_REGISTER = 0xc8,

  // Decrement
  DECREMENT_X_REGISTER = 0xca,
  DECREMENT_Y_REGISTER = 0x88,

  // Jump
  JUMP_ABSOLUTE = 0x4c,
  JUMP_INDIRECT = 0x6c,

  // Branch
  BRANCH_IF_EQUAL = 0xf0,
  BRANCH_IF_NOT_EQUAL = 0xd0,

  // Flags
  SET_CARRY_FLAG = 0x38,
  CLEAR_CARRY_FLAG = 0x18,

  // System
  NO_OPERATION = 0xea,
}

export type AccessOpcode =
  // Load Accumulator
  | Opcode.LOAD_ACCUMULATOR_IMMEDIATE
  | Opcode.LOAD_ACCUMULATOR_ZERO_PAGE
  | Opcode.LOAD_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.LOAD_ACCUMULATOR_ABSOLUTE
  | Opcode.LOAD_ACCUMULATOR_ABSOLUTE_X
  | Opcode.LOAD_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.LOAD_ACCUMULATOR_INDIRECT_X
  | Opcode.LOAD_ACCUMULATOR_INDIRECT_Y

  // Load X Register
  | Opcode.LOAD_X_REGISTER_IMMEDIATE
  | Opcode.LOAD_X_REGISTER_ZERO_PAGE
  | Opcode.LOAD_X_REGISTER_ZERO_PAGE_Y
  | Opcode.LOAD_X_REGISTER_ABSOLUTE
  | Opcode.LOAD_X_REGISTER_ABSOLUTE_Y

  // Load Y Register
  | Opcode.LOAD_Y_REGISTER_IMMEDIATE
  | Opcode.LOAD_Y_REGISTER_ZERO_PAGE
  | Opcode.LOAD_Y_REGISTER_ZERO_PAGE_X
  | Opcode.LOAD_Y_REGISTER_ABSOLUTE
  | Opcode.LOAD_Y_REGISTER_ABSOLUTE_X

  // Store Accumulator
  | Opcode.STORE_ACCUMULATOR_ZERO_PAGE
  | Opcode.STORE_ACCUMULATOR_ZERO_PAGE_X
  | Opcode.STORE_ACCUMULATOR_ABSOLUTE
  | Opcode.STORE_ACCUMULATOR_ABSOLUTE_X
  | Opcode.STORE_ACCUMULATOR_ABSOLUTE_Y
  | Opcode.STORE_ACCUMULATOR_INDIRECT_X
  | Opcode.STORE_ACCUMULATOR_INDIRECT_Y

  // Store X Register
  | Opcode.STORE_X_REGISTER_ZERO_PAGE
  | Opcode.STORE_X_REGISTER_ZERO_PAGE_Y
  | Opcode.STORE_X_REGISTER_ABSOLUTE

  // Store Y Register
  | Opcode.STORE_Y_REGISTER_ZERO_PAGE
  | Opcode.STORE_Y_REGISTER_ZERO_PAGE_X
  | Opcode.STORE_Y_REGISTER_ABSOLUTE;

export type TransferOpcode =
  // X Register <-> Accumulator
  | Opcode.TRANSFER_ACCUMULATOR_TO_X_REGISTER
  | Opcode.TRANSFER_X_REGISTER_TO_ACCUMULATOR

  // Y Register <-> Accumulator
  | Opcode.TRANSFER_ACCUMULATOR_TO_Y_REGISTER
  | Opcode.TRANSFER_Y_REGISTER_TO_ACCUMULATOR;

export type ArithmeticOpcode =
  // Increment
  | Opcode.INCREMENT_X_REGISTER
  | Opcode.INCREMENT_Y_REGISTER

  // Decrement
  | Opcode.DECREMENT_X_REGISTER
  | Opcode.DECREMENT_Y_REGISTER;
